name: Cypress Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node20.11.1-chrome123-ff124-edge123
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, electron]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install NPM dependencies, cache them correctly
    # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: ${{ matrix.browser }}
        # No build step needed for this project
        # Use the project's custom run command
        command: npm run cy:run
        # Recommended: record results to Cypress Cloud
        # record: true
        # Recommended: pass the GitHub token to allow accurately detecting a build vs a re-run build
        # github-token: ${{ secrets.GITHUB_TOKEN }}
        # Recommended: enable parallel builds
        # parallel: true
        # Recommended: enable debugging
        # debug: true
        # Recommended: group test results by spec file
        # group: 'UI - Chrome'
        # Recommended: start the server before running tests
        # start: npm start
        # Recommended: wait for the server to be ready before running tests
        # wait-on: 'http://localhost:3000'
        # Recommended: run tests in headed mode
        # headed: true
        # Recommended: run tests in headless mode
        # headless: true
        # Recommended: run tests in quiet mode
        # quiet: true
        # Recommended: run tests with specific tags
        # tag: 'production,staging'
        # Recommended: run tests with specific spec files
        # spec: 'cypress/e2e/**/*.cy.js'
        # Recommended: run tests with specific environment variables
        # env: 'host=api.dev.local,port=4222'
        # Recommended: run tests with specific config
        config: |
          video=true
          screenshotOnRunFailure=true
          trashAssetsBeforeRuns=true
          videoCompression=32
      env:
        ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
        ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}
        # pass GitHub token to allow accurately detecting a build vs a re-run build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # pass the Dashboard record key as an environment variable
        # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # pass Cypress Cloud project ID as an environment variable
        # CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        CI: true

    - name: Upload all Cypress results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results-${{ matrix.browser }}
        path: cypress/results/
        retention-days: 2
