name: Cypress Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Navegadores para ejecutar las pruebas
        browser: [chrome, firefox, edge]
        # Versiones de Node.js
        node-version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Verify Cypress installation
      run: npx cypress verify

    - name: Run Cypress tests on ${{ matrix.browser }}
      uses: cypress-io/github-action@v6
      with:
        browser: ${{ matrix.browser }}
        headless: true
        record: false
        config: video=true,screenshotOnRunFailure=true
        env: |
          ORANGEHRM_USERNAME=${{ secrets.ORANGEHRM_USERNAME }}
          ORANGEHRM_PASSWORD=${{ secrets.ORANGEHRM_PASSWORD }}
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 120

    - name: Upload screenshots on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-${{ matrix.browser }}-${{ matrix.node-version }}
        path: cypress/results/screenshots
        retention-days: 30

    - name: Upload videos
      uses: actions/upload-artifact@v4
      with:
        name: videos-${{ matrix.browser }}-${{ matrix.node-version }}
        path: cypress/results/videos
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.node-version }}
        path: cypress/results
        retention-days: 30

  # Job para generar reportes consolidados
  generate-reports:
    needs: cypress-run
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Download all test results
      uses: actions/download-artifact@v4
      with:
        path: cypress/results

    - name: Generate consolidated report
      run: |
        # Crear directorio para reportes consolidados
        mkdir -p cypress/consolidated-results
        
        # Copiar todos los resultados
        cp -r cypress/results/* cypress/consolidated-results/ || true
        
        # Generar reporte HTML si existe mochawesome
        if [ -f "cypress/results/mocha/mochawesome.json" ]; then
          npx mochawesome-merge cypress/results/mocha/mochawesome*.json > cypress/consolidated-results/consolidated-report.json
          npx marge cypress/consolidated-results/consolidated-report.json -o cypress/consolidated-results/
        fi

    - name: Upload consolidated reports
      uses: actions/upload-artifact@v4
      with:
        name: consolidated-test-results
        path: cypress/consolidated-results
        retention-days: 90

  # Job para notificaciones (opcional)
  notify:
    needs: [cypress-run, generate-reports]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Cypress tests failed!"
        echo "Check the workflow run for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      
    - name: Notify on success
      if: success()
      run: |
        echo "✅ All Cypress tests passed!"
        echo "Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 